### ISSUE TITLE
thanks for your enjoy！i have a try in sidd dataset of HINet,but it gives me " TypeError: 'NoneType' object is not subscriptable",look for your reply,thank you!

### ISSUE THREAD

**Issue by zxcvads** [megvii-research/tlsc#2]

**Comment by nono0822** [comment]
thanks for your enjoy！i have a try in sidd dataset of HINet,but it gives me " TypeError: 'NoneType' object is not subscriptable",look for your reply,thank you!

**Comment by achusky** [comment]
Thank you for your feedback. We fixed the issue in the latest update.
It is worth mentioning that, the training size and test size for HINet on SIDD dataset are both 256x256, so there is no train-test inconsistency as mentioned in the paper.

**Comment by nono0822** [comment]
> 



> 

thanks for your reply! After your fixed code, i faced another bug:
Traceback (most recent call last):
  File "basicsr/test_tlsc.py", line 68, in <module>
    main()
  File "basicsr/test_tlsc.py", line 64, in main
    rgb2bgr=rgb2bgr, use_image=use_image)
  File "/code/HINet-main/basicsr/models/base_model.py", line 58, in validation
    save_img, rgb2bgr, use_image)
  File "/code/HINet-main/basicsr/models/image_restoration_model.py", line 323, in nondist_validation
    self.grids()      #apply for demo.py
  File "/code/HINet-main/basicsr/models/image_restoration_model.py", line 132, in grids
    num_row = (h - 1) // crop_size + 1
TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'
  0%|                                                                                                                                                       | 0/1280 [00:00<?, ?image/s]

**Comment by nono0822** [comment]
> Thank you for your feedback. We fixed the issue in the latest update. It is worth mentioning that, the training size and test size for HINet on SIDD dataset are both 256x256, so there is no train-test inconsistency as mentioned in the paper.

thanks for your reply! After your fixed code, i faced another bug:
Traceback (most recent call last):
File "basicsr/test_tlsc.py", line 68, in
main()
File "basicsr/test_tlsc.py", line 64, in main
rgb2bgr=rgb2bgr, use_image=use_image)
File "/code/HINet-main/basicsr/models/base_model.py", line 58, in validation
save_img, rgb2bgr, use_image)
File "/code/HINet-main/basicsr/models/image_restoration_model.py", line 323, in nondist_validation
self.grids() #apply for demo.py
File "/code/HINet-main/basicsr/models/image_restoration_model.py", line 132, in grids
num_row = (h - 1) // crop_size + 1
TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'
0%| | 0/1280 [00:00<?, ?image/s]

**Comment by nono0822** [comment]
> Thank you for your feedback. We fixed the issue in the latest update. It is worth mentioning that, the training size and test size for HINet on SIDD dataset are both 256x256, so there is no train-test inconsistency as mentioned in the paper.



> Thank you for your feedback. We fixed the issue in the latest update. It is worth mentioning that, the training size and test size for HINet on SIDD dataset are both 256x256, so there is no train-test inconsistency as mentioned in the paper.

Besides, my sidd datasets preparation is referenced by HINet, https://github.com/megvii-model/HINet/blob/main/scripts/data_preparation/sidd.py,

**Comment by achusky** [comment]
Hi, perhaps you are using an older version of HINet code. You may set `grids: false` in [config](https://github.com/megvii-model/HINet/blob/main/options/test/SIDD/HINet-SIDD-0.5x.yml#L43) or update the code of [image_restoration_model.py](https://github.com/megvii-model/HINet/commit/033ed3a5470950b926b7437c0994a8665fba5ab5).
