### ISSUE TITLE
KeyError: 'state_dict'

### ISSUE THREAD

**Issue by dzw007** [megvii-research/tlsc#23]
作者你好，我在加载Restormer的预训练权重文件motion_deblurring.pth时，发生如下错误
/home/guest/anaconda3/envs/daizhiwei/bin/python /usr/daizhiwei/TLC-main/basicsr/demo.py -opt ../options/demo/demo.yml 
Disable distributed.
Traceback (most recent call last):
  File "/usr/daizhiwei/TLC-main/basicsr/demo.py", line 47, in <module>
    main(root_path)
  File "/usr/daizhiwei/TLC-main/basicsr/demo.py", line 40, in main
    model = create_model(opt)
  File "/usr/daizhiwei/TLC-main/basicsr/models/__init__.py", line 44, in create_model
    model = model_cls(opt)
  File "/usr/daizhiwei/TLC-main/basicsr/models/image_restoration_model.py", line 68, in __init__
    self.load_network(self.net_g, load_path,
  File "/usr/daizhiwei/TLC-main/basicsr/models/base_model.py", line 279, in load_network
    load_net = load_net[param_key]
KeyError: 'state_dict'

但是当我加载HINet-GoPro.pth权重和MPRNet-GoPro.pth却没有发生错误，程序能正常运行，请问这与什么有关呢，该如何解决这个问题？

**Comment by dzw007** [comment]
作者你好，这个问题我解决了。
将源代码：
       if param_key is not None:
            load_net = load_net[param_key]
改为：
       if param_key is not None:
            param_key='params'
            load_net = load_net[param_key]
就能正常运行了
