### ISSUE TITLE
Could not test

### ISSUE THREAD

**Issue by misakshoyan** [megvii-research/tlsc#4]
Hi @achusky.

I am running this line:
'python basicsr/test.py -opt options/test/GoPro/MPRNetLocal-GoPro.yml'
which gives the following error:
'_Traceback (most recent call last):
  File "basicsr/test.py", line 11, in <module>
    from basicsr.data import create_dataloader, create_dataset
  File "/home/misak/Desktop/Projects/tlsc_test/tlsc/basicsr/data/__init__.py", line 17, in <module>
    from basicsr.utils import get_root_logger, scandir
  File "/home/misak/Desktop/Projects/tlsc_test/tlsc/basicsr/utils/__init__.py", line 13, in <module>
    from .create_lmdb import (create_lmdb_for_reds, create_lmdb_for_gopro, create_lmdb_for_rain13k)
ImportError: cannot import name '**create_lmdb_for_gopro**' from 'basicsr.utils.create_lmdb' (/home/misak/Desktop/Projects/tlsc_test/tlsc/basicsr/utils/create_lmdb.py)'_.

Then, I comment the 'create_lmdb_for_gopro, create_lmdb_for_rain13k' from 'basicsr/utils/__init__.py', line 13, and get the next error:
'Traceback (most recent call last):
  File "basicsr/test.py", line 13, in <module>
    from basicsr.train import parse_options
ModuleNotFoundError: **No module named 'basicsr.train'**'

There is no basicsr.train module in this project to import parse_options.

Could you, please, try to look on this?

I have done the installation provided you, downloaded the GoPro dataset and pre-trained model.

Thanks,
Misak

**Comment by achusky** [comment]
Sorry about my mistakes.
I add the missing `parse_options` in the latest update. 
Please try again.

**Comment by TomTomTommi** [comment]
Hi @achusky.
I am running this line:
'python basicsr/demo.py -opt options/demo/demo.yml'
and meet the same problem,
Could you, please, try to look at this?
Thanks!
